### ISSUE TITLE
Eigenpy Verison & CMake Issue

### ISSUE THREAD

**Issue by zhubeilife** [ipab-slmc/eigenpy_catkin#2]
Thanks for sharing this repo, when I use this repo to compile. I am facing two problems.

1- When I use the default eigenpy version v1.5.1, it can't find the boost_python27 cmake. So I change it to v1.5.6, the latest version. It works.

2- I change below cmake copy part,  It seems there is no "site-packages" folder

```cmake
-  COMMAND ${CMAKE_COMMAND} -E copy ${PROJECT_BINARY_DIR}/install/lib/python2.7/
site-packages/eigenpy.so ${CATKIN_DEVEL_PREFIX}/lib/python2.7/site-packages/
+  COMMAND ${CMAKE_COMMAND} -E copy ${PROJECT_BINARY_DIR}/install/lib/python2.7/
dist-packages/eigenpy.so ${CATKIN_DEVEL_PREFIX}/lib/python2.7/site-packages/
```

**Comment by wxmerkt** [comment]
Hi @zhubeilife,
We are changing the way we are packaging eigenpy shortly. The new eigenpy _correctly_ uses dist-packages instead of site-packages as thus many workarounds in this wrapper are no longer needed.

Which version of ROS/Ubuntu are you using and what is your setup?

As soon as the upstream eigenpy has a CMake file we will be deprecating this wrapper and move to a 3rd-party packaged CMake package.

As for workarounds, you have two options:

- Use a version between 1.5.1 and 1.5.6
- Use 1.5.6, but change the copy from site-packages to dist-packages

Hope this helps

**Comment by zhubeilife** [comment]
I am using Kinetic with Debian 10.

Thanks for your help!
